# Generated by Django 3.1.4 on 2021-01-02 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('piece_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('piece_name', models.CharField(choices=[('king', 'KING'), ('queen', 'QUEEN'), ('rook', 'ROOK'), ('bishop', 'BISHOP'), ('knight', 'KNIGHT'), ('pawn', 'PAWN')], max_length=255)),
                ('piece_color', models.CharField(choices=[('white', 'WHITE'), ('black', 'BLACK')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H')], default='PIECE POSITION', max_length=50)),
                ('position_y', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='PIECE POSITION', max_length=50)),
                ('boardpiece_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='piecesapp.pieces')),
            ],
        ),
    ]
