# Generated by Django 3.1.4 on 2021-01-02 19:56

from django.db import migrations, models
import piecesapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('piecesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='boardpiece_id',
            field=models.IntegerField(default=1, verbose_name=piecesapp.models.Pieces),
        ),
    ]
