# Generated by Django 3.1.4 on 2021-01-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecesapp', '0004_auto_20210102_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='piece_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
