# Generated by Django 3.1.4 on 2021-01-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piecesapp', '0005_auto_20210102_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieces',
            name='initial_position_h',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G'), ('h', 'H')], default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='pieces',
            name='initial_position_v',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=1),
        ),
    ]
